# Generated by Django 2.2.4 on 2019-08-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('convert', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FictionChapter',
            fields=[
                ('fiction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiction_chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FictionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiction_class',
                'managed': False,
            },
        ),
    ]
